### ISSUE TITLE
Assistance using the library

### ISSUE THREAD

**Issue by tchouliaras** [marcelo225/django-keycloak-auth#21]
I am trying to use the library, have set everything as described in the documentation. I get the JWT from a keycloak server I have set up and use with java clients. 

However, at my django app, `request.roles` is empty, and `request.userinfo` does not exist. The APIs are all as they would be without any authentication

Maybe some `DEFAULT_AUTHENTICATION_CLASSES` or `AUTH_USER_MODEL` or something similar is needed in the configuration ? 

Currently the only thing I have used is as in README `MIDDLEWARE` entry

Thank you

**Comment by marcelo225** [comment]
Hi, @tchouliaras.

According to [topic](https://github.com/marcelo225/django-keycloak-auth#what-is-it), you must create either some **client roles** or **realm roles** into your Keycloak so that your JWT token has `request.roles` is filled.

I'd rather first option.

Probably your JWT token doesn't carry on these roles. 

Have you already configurated it? 

I recommend you review some configurations of your Keycloak Client.

I brought this [link](https://www.keycloak.org/docs/latest/authorization_services/#_policy_rbac) to understand better how to configure it.

[Check this out as well](https://ramonak.io/posts/keycloak-adding-roles-and-users)

Thank you for getting in touch!

**Comment by tchouliaras** [comment]
@marcelo225 Thank you for your quick reply.

Unfortunately, i cant get it to work, my roles are as below. I have tried setting all kinds of roles. 

```
  "realm_access": {
    "roles": [
      "offline_access",
      "default-roles-fr-realm",
      "uma_authorization",
      "client-admin-role"
    ]
  },
  "resource_access": {
    "realm-management": {
      "roles": [
        "manage-events",
        "manage-clients"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    },
    "fr-client": {
      "roles": [
        "some_role"
      ]
    }
  },
 
```

Should the API be marked as `IsAuthenticated` ? When I add that I get a 403 "Authentication credentials were not provided."

**Comment by marcelo225** [comment]
@tchouliaras, I don't know how you code in your APIView, ViewSet or ModelViewSetdid, but you try to use keycloak_roles in each REST method like this [documentation link](https://github.com/marcelo225/django-keycloak-auth#how-to-use) ? 

Here is an example below:

```python
class TestViewSet(viewsets.ModelViewSet):
   ....
    keycloak_roles = {
        'GET': ['manage-events', 'manage-clients'],
        'POST': ['manage-clients', 'manage-account-links', ],
        'UPDATE': ['manage-account', 'manage-account-links', ],
        'DELETE': ['manage-account', 'manage-account-links', ],
        'PATCH': ['manage-account', 'manage-account-links', 'manage-account-links'],
    }
    ....
```
