### ISSUE TITLE
Access other clients's roles

### ISSUE THREAD

**Issue by gabmich** [marcelo225/django-keycloak-auth#8]
Hi there ! Thanks for your amazing work on this lib first.
We have a project and we have to use following keycloak configuration :

1. a keycloak client for Angular web-app (let's call it keycloak-front)
2. a keycloak bearer-only client for Django Rest API (let's call it keycloak-back)

It is for us impossible to use realms roles (too many users) and to duplicate keycloak-front's roles to keycloak-back's roles (technical reason coming from our system team - no discussion).

Would it be ok for you if I set up a modification for a PR, changing this : 

`client_access = resource_access.get(self.client_id, None) if resource_access is not None else None`

to this ?  

`client_access = resource_access.get(settings.KEYCLOAK_CONFIG['KEYCLOAK_CLIENT_FRONT_ID'], None) if resource_access is not None else None`

KEYCLOAK_CLIENT_FRONT_ID must be added in project's settings.py.

Modification done in "keycloak.py", line 134

Best regards !

Edit : sorry if it's not clear, the goal is to take a list of supported clients, not a single one.

**Comment by marcelo225** [comment]
@gabmich I really appreciated for your comment. 

So... I didn't get straight your idea with 2 keyckoak clients.

I've created this lib because of 1 API for each 1 keycloak client.

If you work with 2 keycloak clients, I suggest you should configure your _keycloak-back client_ as **confidential** in **Access Type** as bellow image:

![image](https://user-images.githubusercontent.com/4791314/112767518-8b2dfc80-8fed-11eb-9017-6e6dc538c440.png)

In the next one, in your keycloak-front client configuration, you should link your keycloak-back client in **Service Account Roles** 

![image](https://user-images.githubusercontent.com/4791314/112765873-a1d05580-8fe5-11eb-8125-aea865a3ac15.png)

So.. you'll have the roles of the backend and frontend inside the same token.

Make sure you checked this bellowing option in your keycloak-fron:
![image](https://user-images.githubusercontent.com/4791314/112767558-b87aaa80-8fed-11eb-803a-57bea4910926.png)

If you can read about documentation how to do it:
https://www.keycloak.org/docs/latest/server_admin/#_service_accounts

Best regards!

**Comment by gabmich** [comment]
@marcelo225 thanks for taking the time to answer !

I cannot change the keycloak configuration, I have to deal with the given one. I only edited one line of code in your lib to make it work with our project, so that's fine for me :-). I don't think a PR will be of any use for most use cases.

Thanks again for your work, and take care !
